#ifndef BLINKMSG_H
#define BLINKMSG_H

enum BLINKMSG {
  BLINKMSG_CONFIG_OK,
  BLINKMSG_SETUP_DIGIPOT_MIN,
  BLINKMSG_SETUP_DIGIPOT_500,
  BLINKMSG_SETUP_ADC_SETPOINT,
};

void blinkmsg(int blinkmsg);
#endif